sample_interval: 1 # The interval, in seconds, at which samples are collected.
report_interval: 10 # The interval, in seconds, at which reports are generated.
#db_file_path: /var/lib/vm_monitor/vm_monitor.db
db_file_path: test_db.db
host_ip: 0.0.0.0
port_number: 8000
